import type { Order, Product } from "./types";

export const categories = ["Semua", "Sate Taichan", "Rice Bowl", "Extras", "Drinks"] as const;

export const products: Product[] = [
  {
    id: "taichan-10",
    name: "Sate Taichan 10 Tusuk",
    description: "Sate ayam juicy, sambal khas, dan perasan jeruk limau.",
    category: "Sate Taichan",
    price: 28000,
    cost: 10500,
    available: true,
    accent: "#f3d7bd",
    imageTone: "from-[#efc6a3] via-[#dc8f61] to-[#8c4730]",
    popular: true,
    options: "spice",
  },
  {
    id: "taichan-5",
    name: "Sate Taichan 5 Tusuk",
    description: "Porsi ringan dengan sambal khas Tempat Taichan.",
    category: "Sate Taichan",
    price: 17000,
    cost: 6500,
    available: true,
    accent: "#f6dfbf",
    imageTone: "from-[#f1d6ae] via-[#dd9f6a] to-[#9c583e]",
    options: "spice",
  },
  {
    id: "rice-bowl",
    name: "Rice Bowl Taichan",
    description: "Nasi hangat, ayam taichan, telur, dan sambal.",
    category: "Rice Bowl",
    price: 27000,
    cost: 10500,
    available: true,
    accent: "#f5e6c7",
    imageTone: "from-[#f6e4b6] via-[#dca36c] to-[#87503d]",
    popular: true,
    options: "rice",
  },
  {
    id: "kulit-crispy",
    name: "Sate Kulit Crispy",
    description: "Kulit ayam renyah dengan bumbu gurih pedas.",
    category: "Sate Taichan",
    price: 22000,
    cost: 8000,
    available: true,
    accent: "#f0d7ae",
    imageTone: "from-[#e4c78f] via-[#bb7746] to-[#713c2c]",
    options: "spice",
  },
  {
    id: "extra-sambal",
    name: "Extra Sambal",
    description: "Sambal taichan ekstra pedas, dibuat fresh.",
    category: "Extras",
    price: 5000,
    cost: 1500,
    available: true,
    accent: "#f2c7b7",
    imageTone: "from-[#efb6a7] via-[#cf5e44] to-[#762f26]",
    options: "none",
  },
  {
    id: "lontong",
    name: "Lontong",
    description: "Lontong pulen untuk teman makan sate.",
    category: "Extras",
    price: 6000,
    cost: 2000,
    available: true,
    accent: "#e8e0b6",
    imageTone: "from-[#eee3bb] via-[#b9af69] to-[#67633d]",
    options: "none",
  },
  {
    id: "es-teh",
    name: "Es Teh Manis",
    description: "Teh melati dingin, manisnya pas.",
    category: "Drinks",
    price: 8000,
    cost: 2000,
    available: true,
    accent: "#d9e4c2",
    imageTone: "from-[#e0e4bf] via-[#a8bf88] to-[#3f6b4a]",
    options: "none",
  },
  {
    id: "jeruk",
    name: "Es Jeruk",
    description: "Jeruk peras segar dengan es batu.",
    category: "Drinks",
    price: 12000,
    cost: 3500,
    available: false,
    accent: "#f4d69d",
    imageTone: "from-[#f5dc9f] via-[#e7a53d] to-[#985626]",
    options: "none",
  },
];

export const initialOrders: Order[] = [
  { id: "ord-1", number: "TT-260917-0142", type: "Dine in", table: "Table 04", items: 3, total: 74000, payment: "QRIS", paymentStatus: "Paid", status: "New", time: "18:42", customer: "Table 04" },
  { id: "ord-2", number: "TT-260917-0141", type: "Takeaway", items: 2, total: 45000, payment: "QRIS", paymentStatus: "Paid", status: "Preparing", time: "18:39", customer: "Takeaway" },
  { id: "ord-3", number: "TT-260917-0140", type: "Dine in", table: "Table 02", items: 5, total: 128000, payment: "Cash", paymentStatus: "Paid", status: "Ready", time: "18:35", customer: "Table 02" },
  { id: "ord-4", number: "TT-260917-0139", type: "Takeaway", items: 1, total: 28000, payment: "QRIS", paymentStatus: "Paid", status: "Completed", time: "18:28", customer: "Walk-in" },
  { id: "ord-5", number: "TT-260917-0138", type: "Dine in", table: "Table 07", items: 4, total: 96000, payment: "QRIS", paymentStatus: "Paid", status: "Completed", time: "18:20", customer: "Table 07" },
];
